## Intro to Attributes
- An **attribute** is a piece of data that lives on an object.
- An **attribute** is a fact, a detail, a characteristic of the object.
- Access an attribute with `object.attribute` syntax.

In [1]:
import pandas as pd 
adjectives	= pd.Series( ["Smart",	"Handsome" ,	"Charming" ,	"Brilliant" ,	"Humble", "Smart"] )
adjectives

0        Smart
1     Handsome
2     Charming
3    Brilliant
4       Humble
5        Smart
dtype: object

In [2]:
adjectives.size

6

In [3]:
adjectives.is_unique

False

In [4]:
adjectives.values

array(['Smart', 'Handsome', 'Charming', 'Brilliant', 'Humble', 'Smart'],
      dtype=object)

In [5]:
adjectives.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
type(adjectives.values)

numpy.ndarray

In [7]:
type(adjectives.index)

pandas.core.indexes.range.RangeIndex

## Parameters and Arguments
- A **parameter** is the name for an expected input to a function/method/class instantiation.
- An **argument** is the concrete value we provide for a parameter during invocation.

In [8]:
fruits = ["Apple", "Orange", "Plum", "Grape", "Blueberry", "Watermelon"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Monday"]

In [9]:
pd.Series(fruits,weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: object

In [10]:
pd.Series(data=fruits, index=weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: object

## Import Series with the pd.read_csv Function
- A CSV is a plain text file that uses line breaks to separate rows and commas to separate row values.
- Pandas ships with many different `read_` functions for different types of files.
- The `read_csv` function accepts many different parameters. The first one specifies the file name/path.
- The `read_csv` function will import the dataset as a **DataFrame**, a 2-dimensional table.
- The `usecols` parameter accepts a list of the column(s) to import.
- The `squeeze` method converts a **DataFrame** to a **Series.**

In [11]:
pd.read_csv("pokemon.csv")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [12]:
pokemon =pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [13]:
google =pd.read_csv("google_stock_price.csv",usecols=["Open"]).squeeze("columns")
google

0         2.493464
1         2.518648
2         2.761511
3         2.773729
4         2.617140
           ...
5154    183.220001
5155    184.320007
5156    185.059998
5157    185.600006
5158    184.070007
Name: Open, Length: 5159, dtype: float64

## The head and tail Methods

- The `head` method returns a number of rows from the top/beginning of the `Series` .
- The `tail` method returns a number of rows from the bottom/end of the `Series` .

In [14]:
pokemon = pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_price.csv", usecols=["Open"]).squeeze("columns")

In [15]:
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [16]:
google.tail()

5154    183.220001
5155    184.320007
5156    185.059998
5157    185.600006
5158    184.070007
Name: Open, dtype: float64

## Passing Series to Python's Built-In Functions

- The `len` function returns the length of the **Series**.
- The `type` function returns the type of an object.
- The `list` function converts the **Series** to a list.
- The `dict` function converts the **Series** to a dictionary.
- The `sorted` function converts the **Series** to a sorted list.
- The `max` function returns the largest value in the **Series**.
- The `min` function returns the smalllest value in the **Series**.

In [17]:
pokemon = pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_price.csv", usecols=["Open"]).squeeze("columns")

In [18]:
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [19]:
len(pokemon)

800

In [20]:
type(pokemon)

pandas.core.series.Series

In [21]:
list(pokemon)[:5]#list(pokemon)

['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur', 'Charmander']

In [22]:
sorted(pokemon)[:5] #sorted(pokemon)

['Abomasnow', 'AbomasnowMega Abomasnow', 'Abra', 'Absol', 'AbsolMega Absol']

In [23]:
sorted(google)[:5]

[2.4732664935985644,
 2.4934637299363867,
 2.511915070778778,
 2.517151267959787,
 2.518647456544224]

In [24]:
dict(pokemon)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'VenusaurMega Venusaur',
 4: 'Charmander',
 5: 'Charmeleon',
 6: 'Charizard',
 7: 'CharizardMega Charizard X',
 8: 'CharizardMega Charizard Y',
 9: 'Squirtle',
 10: 'Wartortle',
 11: 'Blastoise',
 12: 'BlastoiseMega Blastoise',
 13: 'Caterpie',
 14: 'Metapod',
 15: 'Butterfree',
 16: 'Weedle',
 17: 'Kakuna',
 18: 'Beedrill',
 19: 'BeedrillMega Beedrill',
 20: 'Pidgey',
 21: 'Pidgeotto',
 22: 'Pidgeot',
 23: 'PidgeotMega Pidgeot',
 24: 'Rattata',
 25: 'Raticate',
 26: 'Spearow',
 27: 'Fearow',
 28: 'Ekans',
 29: 'Arbok',
 30: 'Pikachu',
 31: 'Raichu',
 32: 'Sandshrew',
 33: 'Sandslash',
 34: 'Nidoran♀',
 35: 'Nidorina',
 36: 'Nidoqueen',
 37: 'Nidoran♂',
 38: 'Nidorino',
 39: 'Nidoking',
 40: 'Clefairy',
 41: 'Clefable',
 42: 'Vulpix',
 43: 'Ninetales',
 44: 'Jigglypuff',
 45: 'Wigglytuff',
 46: 'Zubat',
 47: 'Golbat',
 48: 'Oddish',
 49: 'Gloom',
 50: 'Vileplume',
 51: 'Paras',
 52: 'Parasect',
 53: 'Venonat',
 54: 'Venomoth',
 55: 'Diglett',
 56: 'Dugtrio',
 57: 'Meowth',
 58: 'Persian',
 59: 'Psyduck',
 60: 'Golduck',
 61: 'Mankey',
 62: 'Primeape',
 63: 'Growlithe',
 64: 'Arcanine',
 65: 'Poliwag',
 66: 'Poliwhirl',
 67: 'Poliwrath',
 68: 'Abra',
 69: 'Kadabra',
 70: 'Alakazam',
 71: 'AlakazamMega Alakazam',
 72: 'Machop',
 73: 'Machoke',
 74: 'Machamp',
 75: 'Bellsprout',
 76: 'Weepinbell',
 77: 'Victreebel',
 78: 'Tentacool',
 79: 'Tentacruel',
 80: 'Geodude',
 81: 'Graveler',
 82: 'Golem',
 83: 'Ponyta',
 84: 'Rapidash',
 85: 'Slowpoke',
 86: 'Slowbro',
 87: 'SlowbroMega Slowbro',
 88: 'Magnemite',
 89: 'Magneton',
 90: "Farfetch'd",
 91: 'Doduo',
 92: 'Dodrio',
 93: 'Seel',
 94: 'Dewgong',
 95: 'Grimer',
 96: 'Muk',
 97: 'Shellder',
 98: 'Cloyster',
 99: 'Gastly',
 100: 'Haunter',
 101: 'Gengar',
 102: 'GengarMega Gengar',
 103: 'Onix',
 104: 'Drowzee',
 105: 'Hypno',
 106: 'Krabby',
 107: 'Kingler',
 108: 'Voltorb',
 109: 'Electrode',
 110: 'Exeggcute',
 111: 'Exeggutor',
 112: 'Cubone',
 113: 'Marowak',
 114: 'Hitmonlee',
 115: 'Hitmonchan',
 116: 'Lickitung',
 117: 'Koffing',
 118: 'Weezing',
 119: 'Rhyhorn',
 120: 'Rhydon',
 121: 'Chansey',
 122: 'Tangela',
 123: 'Kangaskhan',
 124: 'KangaskhanMega Kangaskhan',
 125: 'Horsea',
 126: 'Seadra',
 127: 'Goldeen',
 128: 'Seaking',
 129: 'Staryu',
 130: 'Starmie',
 131: 'Mr. Mime',
 132: 'Scyther',
 133: 'Jynx',
 134: 'Electabuzz',
 135: 'Magmar',
 136: 'Pinsir',
 137: 'PinsirMega Pinsir',
 138: 'Tauros',
 139: 'Magikarp',
 140: 'Gyarados',
 141: 'GyaradosMega Gyarados',
 142: 'Lapras',
 143: 'Ditto',
 144: 'Eevee',
 145: 'Vaporeon',
 146: 'Jolteon',
 147: 'Flareon',
 148: 'Porygon',
 149: 'Omanyte',
 150: 'Omastar',
 151: 'Kabuto',
 152: 'Kabutops',
 153: 'Aerodactyl',
 154: 'AerodactylMega Aerodactyl',
 155: 'Snorlax',
 156: 'Articuno',
 157: 'Zapdos',
 158: 'Moltres',
 159: 'Dratini',
 160: 'Dragonair',
 161: 'Dragonite',
 162: 'Mewtwo',
 163: 'MewtwoMega Mewtwo X',
 164: 'MewtwoMega Mewtwo Y',
 165: 'Mew',
 166: 'Chikorita',
 167: 'Bayleef',
 168: 'Meganium',
 169: 'Cyndaquil',
 170: 'Quilava',
 171: 'Typhlosion',
 172: 'Totodile',
 173: 'Croconaw',
 174: 'Feraligatr',
 175: 'Sentret',
 176: 'Furret',
 177: 'Hoothoot',
 178: 'Noctowl',
 179: 'Ledyba',
 180: 'Ledian',
 181: 'Spinarak',
 182: 'Ariados',
 183: 'Crobat',
 184: 'Chinchou',
 185: 'Lanturn',
 186: 'Pichu',
 187: 'Cleffa',
 188: 'Igglybuff',
 189: 'Togepi',
 190: 'Togetic',
 191: 'Natu',
 192: 'Xatu',
 193: 'Mareep',
 194: 'Flaaffy',
 195: 'Ampharos',
 196: 'AmpharosMega Ampharos',
 197: 'Bellossom',
 198: 'Marill',
 199: 'Azumarill',
 200: 'Sudowoodo',
 201: 'Politoed',
 202: 'Hoppip',
 203: 'Skiploom',
 204: 'Jumpluff',
 205: 'Aipom',
 206: 'Sunkern',
 207: 'Sunflora',
 208: 'Yanma',
 209: 'Wooper',
 210: 'Quagsire',
 211: 'Espeon',
 212: 'Umbreon',
 213: 'Murkrow',
 214: 'Slowking',
 215: 'Misdreavus',
 216: 'Unown',
 217: 'Wobbuffet',
 218: 'Girafarig',
 219: 'Pineco',
 220: 'Forretress',
 221: 'Dunsparce',
 222: 'Gligar',
 223: 'Steelix',
 224: 'SteelixMega Steelix',
 225: 'Snubbull',
 226: 'Granbull',
 227: 'Qwilfish',
 228: 'Scizor',
 229: 'ScizorMega Scizor',
 230: 'Shuckle',
 231: 'Heracross',
 232: 'HeracrossMega Heracross',
 233: 'Sneasel',
 234: 'Teddiursa',
 235: 'Ursaring',
 236: 'Slugma',
 237: 'Magcargo',
 238: 'Swinub',
 239: 'Piloswine',
 240: 'Corsola',
 241: 'Remoraid',
 242: 'Octillery',
 243: 'Delibird',
 244: 'Mantine',
 245: 'Skarmory',
 246: 'Houndour',
 247: 'Houndoom',
 248: 'HoundoomMega Houndoom',
 249: 'Kingdra',
 250: 'Phanpy',
 251: 'Donphan',
 252: 'Porygon2',
 253: 'Stantler',
 254: 'Smeargle',
 255: 'Tyrogue',
 256: 'Hitmontop',
 257: 'Smoochum',
 258: 'Elekid',
 259: 'Magby',
 260: 'Miltank',
 261: 'Blissey',
 262: 'Raikou',
 263: 'Entei',
 264: 'Suicune',
 265: 'Larvitar',
 266: 'Pupitar',
 267: 'Tyranitar',
 268: 'TyranitarMega Tyranitar',
 269: 'Lugia',
 270: 'Ho-oh',
 271: 'Celebi',
 272: 'Treecko',
 273: 'Grovyle',
 274: 'Sceptile',
 275: 'SceptileMega Sceptile',
 276: 'Torchic',
 277: 'Combusken',
 278: 'Blaziken',
 279: 'BlazikenMega Blaziken',
 280: 'Mudkip',
 281: 'Marshtomp',
 282: 'Swampert',
 283: 'SwampertMega Swampert',
 284: 'Poochyena',
 285: 'Mightyena',
 286: 'Zigzagoon',
 287: 'Linoone',
 288: 'Wurmple',
 289: 'Silcoon',
 290: 'Beautifly',
 291: 'Cascoon',
 292: 'Dustox',
 293: 'Lotad',
 294: 'Lombre',
 295: 'Ludicolo',
 296: 'Seedot',
 297: 'Nuzleaf',
 298: 'Shiftry',
 299: 'Taillow',
 300: 'Swellow',
 301: 'Wingull',
 302: 'Pelipper',
 303: 'Ralts',
 304: 'Kirlia',
 305: 'Gardevoir',
 306: 'GardevoirMega Gardevoir',
 307: 'Surskit',
 308: 'Masquerain',
 309: 'Shroomish',
 310: 'Breloom',
 311: 'Slakoth',
 312: 'Vigoroth',
 313: 'Slaking',
 314: 'Nincada',
 315: 'Ninjask',
 316: 'Shedinja',
 317: 'Whismur',
 318: 'Loudred',
 319: 'Exploud',
 320: 'Makuhita',
 321: 'Hariyama',
 322: 'Azurill',
 323: 'Nosepass',
 324: 'Skitty',
 325: 'Delcatty',
 326: 'Sableye',
 327: 'SableyeMega Sableye',
 328: 'Mawile',
 329: 'MawileMega Mawile',
 330: 'Aron',
 331: 'Lairon',
 332: 'Aggron',
 333: 'AggronMega Aggron',
 334: 'Meditite',
 335: 'Medicham',
 336: 'MedichamMega Medicham',
 337: 'Electrike',
 338: 'Manectric',
 339: 'ManectricMega Manectric',
 340: 'Plusle',
 341: 'Minun',
 342: 'Volbeat',
 343: 'Illumise',
 344: 'Roselia',
 345: 'Gulpin',
 346: 'Swalot',
 347: 'Carvanha',
 348: 'Sharpedo',
 349: 'SharpedoMega Sharpedo',
 350: 'Wailmer',
 351: 'Wailord',
 352: 'Numel',
 353: 'Camerupt',
 354: 'CameruptMega Camerupt',
 355: 'Torkoal',
 356: 'Spoink',
 357: 'Grumpig',
 358: 'Spinda',
 359: 'Trapinch',
 360: 'Vibrava',
 361: 'Flygon',
 362: 'Cacnea',
 363: 'Cacturne',
 364: 'Swablu',
 365: 'Altaria',
 366: 'AltariaMega Altaria',
 367: 'Zangoose',
 368: 'Seviper',
 369: 'Lunatone',
 370: 'Solrock',
 371: 'Barboach',
 372: 'Whiscash',
 373: 'Corphish',
 374: 'Crawdaunt',
 375: 'Baltoy',
 376: 'Claydol',
 377: 'Lileep',
 378: 'Cradily',
 379: 'Anorith',
 380: 'Armaldo',
 381: 'Feebas',
 382: 'Milotic',
 383: 'Castform',
 384: 'Kecleon',
 385: 'Shuppet',
 386: 'Banette',
 387: 'BanetteMega Banette',
 388: 'Duskull',
 389: 'Dusclops',
 390: 'Tropius',
 391: 'Chimecho',
 392: 'Absol',
 393: 'AbsolMega Absol',
 394: 'Wynaut',
 395: 'Snorunt',
 396: 'Glalie',
 397: 'GlalieMega Glalie',
 398: 'Spheal',
 399: 'Sealeo',
 400: 'Walrein',
 401: 'Clamperl',
 402: 'Huntail',
 403: 'Gorebyss',
 404: 'Relicanth',
 405: 'Luvdisc',
 406: 'Bagon',
 407: 'Shelgon',
 408: 'Salamence',
 409: 'SalamenceMega Salamence',
 410: 'Beldum',
 411: 'Metang',
 412: 'Metagross',
 413: 'MetagrossMega Metagross',
 414: 'Regirock',
 415: 'Regice',
 416: 'Registeel',
 417: 'Latias',
 418: 'LatiasMega Latias',
 419: 'Latios',
 420: 'LatiosMega Latios',
 421: 'Kyogre',
 422: 'KyogrePrimal Kyogre',
 423: 'Groudon',
 424: 'GroudonPrimal Groudon',
 425: 'Rayquaza',
 426: 'RayquazaMega Rayquaza',
 427: 'Jirachi',
 428: 'DeoxysNormal Forme',
 429: 'DeoxysAttack Forme',
 430: 'DeoxysDefense Forme',
 431: 'DeoxysSpeed Forme',
 432: 'Turtwig',
 433: 'Grotle',
 434: 'Torterra',
 435: 'Chimchar',
 436: 'Monferno',
 437: 'Infernape',
 438: 'Piplup',
 439: 'Prinplup',
 440: 'Empoleon',
 441: 'Starly',
 442: 'Staravia',
 443: 'Staraptor',
 444: 'Bidoof',
 445: 'Bibarel',
 446: 'Kricketot',
 447: 'Kricketune',
 448: 'Shinx',
 449: 'Luxio',
 450: 'Luxray',
 451: 'Budew',
 452: 'Roserade',
 453: 'Cranidos',
 454: 'Rampardos',
 455: 'Shieldon',
 456: 'Bastiodon',
 457: 'Burmy',
 458: 'WormadamPlant Cloak',
 459: 'WormadamSandy Cloak',
 460: 'WormadamTrash Cloak',
 461: 'Mothim',
 462: 'Combee',
 463: 'Vespiquen',
 464: 'Pachirisu',
 465: 'Buizel',
 466: 'Floatzel',
 467: 'Cherubi',
 468: 'Cherrim',
 469: 'Shellos',
 470: 'Gastrodon',
 471: 'Ambipom',
 472: 'Drifloon',
 473: 'Drifblim',
 474: 'Buneary',
 475: 'Lopunny',
 476: 'LopunnyMega Lopunny',
 477: 'Mismagius',
 478: 'Honchkrow',
 479: 'Glameow',
 480: 'Purugly',
 481: 'Chingling',
 482: 'Stunky',
 483: 'Skuntank',
 484: 'Bronzor',
 485: 'Bronzong',
 486: 'Bonsly',
 487: 'Mime Jr.',
 488: 'Happiny',
 489: 'Chatot',
 490: 'Spiritomb',
 491: 'Gible',
 492: 'Gabite',
 493: 'Garchomp',
 494: 'GarchompMega Garchomp',
 495: 'Munchlax',
 496: 'Riolu',
 497: 'Lucario',
 498: 'LucarioMega Lucario',
 499: 'Hippopotas',
 500: 'Hippowdon',
 501: 'Skorupi',
 502: 'Drapion',
 503: 'Croagunk',
 504: 'Toxicroak',
 505: 'Carnivine',
 506: 'Finneon',
 507: 'Lumineon',
 508: 'Mantyke',
 509: 'Snover',
 510: 'Abomasnow',
 511: 'AbomasnowMega Abomasnow',
 512: 'Weavile',
 513: 'Magnezone',
 514: 'Lickilicky',
 515: 'Rhyperior',
 516: 'Tangrowth',
 517: 'Electivire',
 518: 'Magmortar',
 519: 'Togekiss',
 520: 'Yanmega',
 521: 'Leafeon',
 522: 'Glaceon',
 523: 'Gliscor',
 524: 'Mamoswine',
 525: 'Porygon-Z',
 526: 'Gallade',
 527: 'GalladeMega Gallade',
 528: 'Probopass',
 529: 'Dusknoir',
 530: 'Froslass',
 531: 'Rotom',
 532: 'RotomHeat Rotom',
 533: 'RotomWash Rotom',
 534: 'RotomFrost Rotom',
 535: 'RotomFan Rotom',
 536: 'RotomMow Rotom',
 537: 'Uxie',
 538: 'Mesprit',
 539: 'Azelf',
 540: 'Dialga',
 541: 'Palkia',
 542: 'Heatran',
 543: 'Regigigas',
 544: 'GiratinaAltered Forme',
 545: 'GiratinaOrigin Forme',
 546: 'Cresselia',
 547: 'Phione',
 548: 'Manaphy',
 549: 'Darkrai',
 550: 'ShayminLand Forme',
 551: 'ShayminSky Forme',
 552: 'Arceus',
 553: 'Victini',
 554: 'Snivy',
 555: 'Servine',
 556: 'Serperior',
 557: 'Tepig',
 558: 'Pignite',
 559: 'Emboar',
 560: 'Oshawott',
 561: 'Dewott',
 562: 'Samurott',
 563: 'Patrat',
 564: 'Watchog',
 565: 'Lillipup',
 566: 'Herdier',
 567: 'Stoutland',
 568: 'Purrloin',
 569: 'Liepard',
 570: 'Pansage',
 571: 'Simisage',
 572: 'Pansear',
 573: 'Simisear',
 574: 'Panpour',
 575: 'Simipour',
 576: 'Munna',
 577: 'Musharna',
 578: 'Pidove',
 579: 'Tranquill',
 580: 'Unfezant',
 581: 'Blitzle',
 582: 'Zebstrika',
 583: 'Roggenrola',
 584: 'Boldore',
 585: 'Gigalith',
 586: 'Woobat',
 587: 'Swoobat',
 588: 'Drilbur',
 589: 'Excadrill',
 590: 'Audino',
 591: 'AudinoMega Audino',
 592: 'Timburr',
 593: 'Gurdurr',
 594: 'Conkeldurr',
 595: 'Tympole',
 596: 'Palpitoad',
 597: 'Seismitoad',
 598: 'Throh',
 599: 'Sawk',
 600: 'Sewaddle',
 601: 'Swadloon',
 602: 'Leavanny',
 603: 'Venipede',
 604: 'Whirlipede',
 605: 'Scolipede',
 606: 'Cottonee',
 607: 'Whimsicott',
 608: 'Petilil',
 609: 'Lilligant',
 610: 'Basculin',
 611: 'Sandile',
 612: 'Krokorok',
 613: 'Krookodile',
 614: 'Darumaka',
 615: 'DarmanitanStandard Mode',
 616: 'DarmanitanZen Mode',
 617: 'Maractus',
 618: 'Dwebble',
 619: 'Crustle',
 620: 'Scraggy',
 621: 'Scrafty',
 622: 'Sigilyph',
 623: 'Yamask',
 624: 'Cofagrigus',
 625: 'Tirtouga',
 626: 'Carracosta',
 627: 'Archen',
 628: 'Archeops',
 629: 'Trubbish',
 630: 'Garbodor',
 631: 'Zorua',
 632: 'Zoroark',
 633: 'Minccino',
 634: 'Cinccino',
 635: 'Gothita',
 636: 'Gothorita',
 637: 'Gothitelle',
 638: 'Solosis',
 639: 'Duosion',
 640: 'Reuniclus',
 641: 'Ducklett',
 642: 'Swanna',
 643: 'Vanillite',
 644: 'Vanillish',
 645: 'Vanilluxe',
 646: 'Deerling',
 647: 'Sawsbuck',
 648: 'Emolga',
 649: 'Karrablast',
 650: 'Escavalier',
 651: 'Foongus',
 652: 'Amoonguss',
 653: 'Frillish',
 654: 'Jellicent',
 655: 'Alomomola',
 656: 'Joltik',
 657: 'Galvantula',
 658: 'Ferroseed',
 659: 'Ferrothorn',
 660: 'Klink',
 661: 'Klang',
 662: 'Klinklang',
 663: 'Tynamo',
 664: 'Eelektrik',
 665: 'Eelektross',
 666: 'Elgyem',
 667: 'Beheeyem',
 668: 'Litwick',
 669: 'Lampent',
 670: 'Chandelure',
 671: 'Axew',
 672: 'Fraxure',
 673: 'Haxorus',
 674: 'Cubchoo',
 675: 'Beartic',
 676: 'Cryogonal',
 677: 'Shelmet',
 678: 'Accelgor',
 679: 'Stunfisk',
 680: 'Mienfoo',
 681: 'Mienshao',
 682: 'Druddigon',
 683: 'Golett',
 684: 'Golurk',
 685: 'Pawniard',
 686: 'Bisharp',
 687: 'Bouffalant',
 688: 'Rufflet',
 689: 'Braviary',
 690: 'Vullaby',
 691: 'Mandibuzz',
 692: 'Heatmor',
 693: 'Durant',
 694: 'Deino',
 695: 'Zweilous',
 696: 'Hydreigon',
 697: 'Larvesta',
 698: 'Volcarona',
 699: 'Cobalion',
 700: 'Terrakion',
 701: 'Virizion',
 702: 'TornadusIncarnate Forme',
 703: 'TornadusTherian Forme',
 704: 'ThundurusIncarnate Forme',
 705: 'ThundurusTherian Forme',
 706: 'Reshiram',
 707: 'Zekrom',
 708: 'LandorusIncarnate Forme',
 709: 'LandorusTherian Forme',
 710: 'Kyurem',
 711: 'KyuremBlack Kyurem',
 712: 'KyuremWhite Kyurem',
 713: 'KeldeoOrdinary Forme',
 714: 'KeldeoResolute Forme',
 715: 'MeloettaAria Forme',
 716: 'MeloettaPirouette Forme',
 717: 'Genesect',
 718: 'Chespin',
 719: 'Quilladin',
 720: 'Chesnaught',
 721: 'Fennekin',
 722: 'Braixen',
 723: 'Delphox',
 724: 'Froakie',
 725: 'Frogadier',
 726: 'Greninja',
 727: 'Bunnelby',
 728: 'Diggersby',
 729: 'Fletchling',
 730: 'Fletchinder',
 731: 'Talonflame',
 732: 'Scatterbug',
 733: 'Spewpa',
 734: 'Vivillon',
 735: 'Litleo',
 736: 'Pyroar',
 737: 'Flabébé',
 738: 'Floette',
 739: 'Florges',
 740: 'Skiddo',
 741: 'Gogoat',
 742: 'Pancham',
 743: 'Pangoro',
 744: 'Furfrou',
 745: 'Espurr',
 746: 'MeowsticMale',
 747: 'MeowsticFemale',
 748: 'Honedge',
 749: 'Doublade',
 750: 'AegislashBlade Forme',
 751: 'AegislashShield Forme',
 752: 'Spritzee',
 753: 'Aromatisse',
 754: 'Swirlix',
 755: 'Slurpuff',
 756: 'Inkay',
 757: 'Malamar',
 758: 'Binacle',
 759: 'Barbaracle',
 760: 'Skrelp',
 761: 'Dragalge',
 762: 'Clauncher',
 763: 'Clawitzer',
 764: 'Helioptile',
 765: 'Heliolisk',
 766: 'Tyrunt',
 767: 'Tyrantrum',
 768: 'Amaura',
 769: 'Aurorus',
 770: 'Sylveon',
 771: 'Hawlucha',
 772: 'Dedenne',
 773: 'Carbink',
 774: 'Goomy',
 775: 'Sliggoo',
 776: 'Goodra',
 777: 'Klefki',
 778: 'Phantump',
 779: 'Trevenant',
 780: 'PumpkabooAverage Size',
 781: 'PumpkabooSmall Size',
 782: 'PumpkabooLarge Size',
 783: 'PumpkabooSuper Size',
 784: 'GourgeistAverage Size',
 785: 'GourgeistSmall Size',
 786: 'GourgeistLarge Size',
 787: 'GourgeistSuper Size',
 788: 'Bergmite',
 789: 'Avalugg',
 790: 'Noibat',
 791: 'Noivern',
 792: 'Xerneas',
 793: 'Yveltal',
 794: 'Zygarde50% Forme',
 795: 'Diancie',
 796: 'DiancieMega Diancie',
 797: 'HoopaHoopa Confined',
 798: 'HoopaHoopa Unbound',
 799: 'Volcanion'}

In [25]:
max(google)

203.38999938964844

In [26]:
min(google)

2.4732664935985644

In [27]:
max(pokemon)

'Zygarde50% Forme'

In [28]:
min(pokemon)

'Abomasnow'

## Check for Inclusion with Python's in Keyword

- The `in` keyword checks if a value exists within an object.
- The `in` keyword will look for a value in the **Series's** index.
- Use the `index` and `values` attributes to access "nested" objects within the **Series's**.
- Combine the `in` keyword with `values` to search within the **Series's** values.

In [29]:
pokemon = pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_price.csv", usecols=["Open"]).squeeze("columns")

In [30]:
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [31]:
"Bulbasaur" in pokemon

False

In [32]:
0 in pokemon

True

In [33]:
pokemon.index

RangeIndex(start=0, stop=800, step=1)

In [34]:
"Bulbasaur" in pokemon.values

True

## The sort_values Method

- The `sort_values` method sorts a **Series** values in order.
- By default, pandas applies an ascending sort (smallest to largest).
- Customize the sort order with the `ascending` parameter.

In [35]:
pokemon = pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_price.csv", usecols=["Open"]).squeeze("columns")
google.head()

0    2.493464
1    2.518648
2    2.761511
3    2.773729
4    2.617140
Name: Open, dtype: float64

In [36]:
google.sort_values()

10        2.473266
0         2.493464
13        2.511915
11        2.517151
12        2.518647
           ...
5139    199.059998
5138    199.070007
5147    200.690002
5146    202.000000
5148    203.389999
Name: Open, Length: 5159, dtype: float64

In [37]:
google.sort_values(ascending=False)

5148    203.389999
5146    202.000000
5147    200.690002
5138    199.070007
5139    199.059998
           ...
12        2.518647
11        2.517151
13        2.511915
0         2.493464
10        2.473266
Name: Open, Length: 5159, dtype: float64

In [38]:
google.sort_values(ascending=False).head()

5148    203.389999
5146    202.000000
5147    200.690002
5138    199.070007
5139    199.059998
Name: Open, dtype: float64

## The sort_index Method

- The `sort_index` method sorts a **Series** by its index.
- The `sort_index` method also accepts an `ascending` parameter to set sort order.

In [39]:
pd.read_csv("pokemon.csv",index_col="Name").squeeze("columns")
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [40]:
pokemon.sort_index()

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

## Extract Series Value by Index Position

- Use the `iloc` accessor to extract a **Series** value by its index position.
- `iloc` is short for "index location".
- Python's list slicing syntaxes (slices, slices from start, slices to end, etc.) are supported with **Series** objects.

In [41]:
pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [42]:
pokemon.iloc[0]

'Bulbasaur'

In [43]:
pokemon.iloc[[100,200,300]]

100      Haunter
200    Sudowoodo
300      Swellow
Name: Name, dtype: object

In [44]:
pokemon.iloc[27:36]

27       Fearow
28        Ekans
29        Arbok
30      Pikachu
31       Raichu
32    Sandshrew
33    Sandslash
34     Nidoran♀
35     Nidorina
Name: Name, dtype: object

In [45]:
pokemon.iloc[0:6]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
5               Charmeleon
Name: Name, dtype: object

## Extract Series Value by Index Label

- Use the `loc` accessor to extract a **Series** value by its index label.
- Pass a list to extract multiple values by index label.
- If one index label/position in the list does not exist, Pandas will raise an error.

In [54]:
pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
pokemon.head()

Empty DataFrame
Columns: []
Index: [Bulbasaur, Ivysaur, Venusaur, VenusaurMega Venusaur, Charmander]

In [51]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"], index_col="Name").squeeze("columns")
pokemon.loc["Bulbasaur"]

Series([], Name: Bulbasaur, dtype: float64)

In [52]:
pokemon.loc["Bulbasaur"]

Series([], Name: Bulbasaur, dtype: float64)

In [49]:
pokemon[pokemon == "Bulbasaur"]

0    Bulbasaur
Name: Name, dtype: object

## The get Method on a Series

- The `get` method extracts a Series value by index label. It is an alternative option to square brackets.
- The `get` method's second argument sets the fallback value to return if the label/position does not exist.

In [59]:
pokemon=pd.read_csv("pokemon.csv",index_col="Name").squeeze("columns")
pokemon.head()

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False

In [63]:
pokemon.get('Moltres')

In [62]:
pokemon.loc["Moltres"]

#                146
Type 1          Fire
Type 2        Flying
Total            580
HP                90
Attack           100
Defense           90
Sp. Atk          125
Sp. Def           85
Speed             90
Generation         1
Legendary       True
Name: Moltres, dtype: object

## Overwrite a Series Value
- Use the `ioc/ iloc` accessor to target an index label/position, then use an equal sign to provide a new value.

In [64]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]) .squeeze("columns")
pokemon. head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [65]:
pokemon.iloc[0]="Borisaur" #inventing new pokemon at index 0 we have repelace the previsous with the new

In [66]:
pokemon.head()

0                 Borisaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [67]:
pokemon.iloc[[1,2,4]] = ["Firemon","Flammon","Blazemon"]

In [68]:
pokemon.head()

0                 Borisaur
1                  Firemon
2                  Flammon
3    VenusaurMega Venusaur
4                 Blazemon
Name: Name, dtype: object

In [73]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name") .squeeze("columns")
pokemon. head()

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False

In [76]:
pokemon.loc["Bulbasaur", "Name"] = "Awesomsor"

In [77]:
pokemon.head()

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name
Name,,,,,,,,,,,,,
Bulbasaur,1,Awesomsor,Poison,318,45,49,49,65,65,45,1,False,Awesomsor
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False,NaN
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False,NaN
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False,NaN
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False,NaN

## The copy Method

- A **copy** is a duplicate/replica of an object.
- Changes to a copy do not modify the original object.
- A **view** is a different way of looking at the same data.
- Changes to a view do modify the original object.
- The `copy` method creates a copy of a pandas object.

In [90]:
pokemon_df=pd.read_csv("pokemon.csv",usecols=["Name"])
pokemon_series = pokemon_df.squeeze("columns").copy()
# pokemon.head()

In [84]:
pokemon_df

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[800 rows x 1 columns]

In [85]:
pokemon_series

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [86]:
pokemon_series[0]

'Bulbasaur'

In [87]:
pokemon_series[0]="Whatever"

In [88]:
pokemon_series.head()

0                 Whatever
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [91]:
pokemon_df #while making the copy there is no change in the original csv file(dataframe)

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[800 rows x 1 columns]

## Math Methods on Series Objects

- The `count` method returns the number of values in the **Series**. It excludes missing values; the size attribute includes missing values.
- The `sum` method adds together the **Series**'s values.
- The `product` method multiplies together the **Series's** values.
- The `mean` method calculates the average of the **Series's** values.
- The `std` method calculates the standard deviation of the **Series's** values.
- The `max` method returns the largest value in the **Series**.
- The `min` method returns the smallest value in the **Series**.
- The `median` method returns the median of the **Series** (the value in the middle).
- The `mode` method returns the mode of the **Series** (the most frequent value).
- The `describe` method returns a summary with various mathematical calculations.

In [95]:
google = pd.read_csv("google_stock_price.csv", usecols=["Open"]).squeeze("columns")
google.head()

0    2.493464
1    2.518648
2    2.761511
3    2.773729
4    2.617140
Name: Open, dtype: float64

In [96]:
google.count() #exclude the missing values

np.int64(5159)

In [98]:
google.size #include the missing values

5159

In [99]:
google.sum()

np.float64(250884.2474624056)

In [100]:
google.product()

C:\Users\suyas\anaconda3\Lib\site-packages\numpy\_core\_methods.py:55: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

np.float64(inf)

In [101]:
pd.Series([1,2,3]).product()

np.int64(6)

In [103]:
google.mean() #average

np.float64(48.63040268703345)

In [104]:
google.std() #Standard deviation measures how far data values typically spread out from the mean.

47.210441769485506

In [105]:
google.max()

203.38999938964844

In [106]:
google.min()

2.4732664935985644

In [107]:
google.median()

28.114083738931352

In [108]:
google.mode()

0         2.473266
1         2.493464
2         2.511915
3         2.517151
4         2.518647
           ...
5154    199.059998
5155    199.070007
5156    200.690002
5157    202.000000
5158    203.389999
Name: Open, Length: 5159, dtype: float64

In [109]:
pd.Series([1,2,3,2,4]).mode()

0    2
dtype: int64

In [110]:
google.describe()

count    5159.000000
mean       48.630403
std        47.210442
min         2.473266
25%        13.169726
50%        28.114084
75%        64.299166
max       203.389999
Name: Open, dtype: float64

## Broadcasting

- **Broadcasting** describes the process of applying an arithmetic operation to an array (i.e., a **Series**).
- We can combine mathematical operators with a **Series** to apply the mathematical operation to every value.
- There are also methods to accomplish the same results ( `add`, `sub`, `mul`, `div` , etc.)

In [111]:
google = pd.read_csv("google_stock_price.csv",usecols=["Open"]).squeeze("columns")
google.head()

0    2.493464
1    2.518648
2    2.761511
3    2.773729
4    2.617140
Name: Open, dtype: float64

In [113]:
google.add(10)
google + 10

0        12.493464
1        12.518648
2        12.761511
3        12.773729
4        12.617140
           ...
5154    193.220001
5155    194.320007
5156    195.059998
5157    195.600006
5158    194.070007
Name: Open, Length: 5159, dtype: float64

In [114]:
google.sub(10)

0        -7.506536
1        -7.481352
2        -7.238489
3        -7.226271
4        -7.382860
           ...
5154    173.220001
5155    174.320007
5156    175.059998
5157    175.600006
5158    174.070007
Name: Open, Length: 5159, dtype: float64

In [115]:
google -10

0        -7.506536
1        -7.481352
2        -7.238489
3        -7.226271
4        -7.382860
           ...
5154    173.220001
5155    174.320007
5156    175.059998
5157    175.600006
5158    174.070007
Name: Open, Length: 5159, dtype: float64

In [116]:
google.mul(1.25)

0         3.116830
1         3.148309
2         3.451889
3         3.467161
4         3.271425
           ...
5154    229.025002
5155    230.400009
5156    231.324997
5157    232.000008
5158    230.087509
Name: Open, Length: 5159, dtype: float64

In [117]:
google*1.25

0         3.116830
1         3.148309
2         3.451889
3         3.467161
4         3.271425
           ...
5154    229.025002
5155    230.400009
5156    231.324997
5157    232.000008
5158    230.087509
Name: Open, Length: 5159, dtype: float64

## The value_counts Method
- The `value_counts` method returns the number of times each unique value occurs in the **Series**.
- The `normalize` parameter returns the relative frequencies/percentages of the values instead of the counts.

In [118]:
pokemon = pd.read_csv("pokemon.csv",index_col="Name").squeeze("columns")
pokemon.head()

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False

In [123]:
df = pd.read_csv("pokemon.csv", index_col="Name",usecols=["Name", "Type 1"])
df.head()

                      Type 1
Name
Bulbasaur              Grass
Ivysaur                Grass
Venusaur               Grass
VenusaurMega Venusaur  Grass
Charmander              Fire

In [124]:
df.value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ghost        32
Ground       32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [125]:
df.value_counts(ascending=True)

Type 1
Flying        4
Fairy        17
Ice          24
Fighting     27
Steel        27
Poison       28
Dark         31
Ghost        32
Dragon       32
Ground       32
Electric     44
Rock         44
Fire         52
Psychic      57
Bug          69
Grass        70
Normal       98
Water       112
Name: count, dtype: int64

In [126]:
df.value_counts(normalize=True)

Type 1
Water       0.14000
Normal      0.12250
Grass       0.08750
Bug         0.08625
Psychic     0.07125
Fire        0.06500
Electric    0.05500
Rock        0.05500
Ghost       0.04000
Ground      0.04000
Dragon      0.04000
Dark        0.03875
Poison      0.03500
Fighting    0.03375
Steel       0.03375
Ice         0.03000
Fairy       0.02125
Flying      0.00500
Name: proportion, dtype: float64

In [127]:
df.value_counts(normalize=True)*100

Type 1
Water       14.000
Normal      12.250
Grass        8.750
Bug          8.625
Psychic      7.125
Fire         6.500
Electric     5.500
Rock         5.500
Ghost        4.000
Ground       4.000
Dragon       4.000
Dark         3.875
Poison       3.500
Fighting     3.375
Steel        3.375
Ice          3.000
Fairy        2.125
Flying       0.500
Name: proportion, dtype: float64

## The apply Method

- The `apply` method accepts a function. It invokes that function on every `Series` value.

In [128]:
pokemon = pd.read_csv("pokemon.csv",usecols=["Name"]).squeeze("columns")
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [132]:
pokemon.apply(len)

0       9
1       7
2       8
3      21
4      10
       ..
795     7
796    19
797    19
798    18
799     9
Name: Name, Length: 800, dtype: int64

In [133]:
def count_of_a(pokemon):
    return pokemon.count("a")
pokemon.apply(count_of_a)

0      2
1      1
2      1
3      3
4      2
      ..
795    1
796    3
797    2
798    2
799    1
Name: Name, Length: 800, dtype: int64

## The map Method

- The `map` method "maps" or connects each **Series** values to another value.
- We can pass the method a dictionary or a **Series**. Both types connects keys to values.
- The `map` method uses our argument to connect or bridge together the values.

In [135]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name",usecols=["Name", "Type 1"])
pokemon.head()

                      Type 1
Name
Bulbasaur              Grass
Ivysaur                Grass
Venusaur               Grass
VenusaurMega Venusaur  Grass
Charmander              Fire

In [138]:
attack_powers = {
    "Grass": 10,
    "Fire": 15,
    "Water": 15,
    "Fairy, Fighting": 20,
    "Grass, Psychic": 50
}

In [140]:
pokemon["Type 1"].map(attack_powers)

Name
Bulbasaur                10.0
Ivysaur                  10.0
Venusaur                 10.0
VenusaurMega Venusaur    10.0
Charmander               15.0
                         ...
Diancie                   NaN
DiancieMega Diancie       NaN
HoopaHoopa Confined       NaN
HoopaHoopa Unbound        NaN
Volcanion                15.0
Name: Type 1, Length: 800, dtype: float64

In [142]:
attack_powers = pd.Series({
    "Grass": 10,
    "Fire": 15,
    "Water": 15,
    "Fairy, Fighting": 20,
    "Grass, Psychic": 50
})
attack_powers.head()

Grass              10
Fire               15
Water              15
Fairy, Fighting    20
Grass, Psychic     50
dtype: int64